---
# pkginstall.yml - Install packages that we'd like to have
- name: Convenience packages
  yum: name={{ item }} state=installed
  with_items:
    - vim
    - tmux
    - git
    - facter
  tags:
    - pkginstall
