%YAML 1.1
---
elastic_baseurl: https://artifacts.elastic.co/packages/5.x/yum
elastic_gpgurl: https://artifacts.elastic.co/GPG-KEY-elasticsearch

# Elasticsearch instance configuration variables
es_user: elasticsearch
es_group: elasticsearch
es_data_dir: "{{ rock_data_dir }}/elasticsearch"
es_cluster_name: rocknsm
es_node_name: "{{ rock_hostname }}"
es_mem: "{{ (ansible_memtotal_mb // 1024 // 2) if (ansible_memtotal_mb // 1024) < 64 else 31 }}"
es_url: "http://localhost:9200"
es_memlock_override: |
  [Service]
  LimitMEMLOCK=infinity
  
# Add in the custom rock dashboards
rock_dashboards_repo: https://github.com/rocknsm/rock-dashboards.git
rock_dashboards_branch: master
rock_dashboards_url: "https://github.com/rocknsm/rock-dashboards/archive/{{ rock_dashboards_branch }}.tar.gz"
rock_dashboards_filename: "rock-dashboards_{{ rock_dashboards_branch | replace('/', '-') }}.tar.gz"
rock_dashboards_version: 2.0