---
######################################################
################# Data Directory #####################
######################################################
###############
##### NOTE ####
###############
# You will want to remount this to your "good" storage after the build.
# This is just to make sure all the paths in the configs are proper.
###############
- name: Create ROCK data dir
  file:
    path: "{{ rock_data_dir }}"
    mode: 0755
    owner: "{{ rock_data_user }}"
    group: "{{ rock_data_group }}"
    state: directory

- name: Create ROCK NSM directory
  file:
    path: "{{ rocknsm_dir }}"
    mode: 0755
    owner: root
    group: root
    state: directory

######################################################
######### Configure the monitoring interface #########
######################################################
- name: Set monitor interface config
  template:
    src: templates/ifcfg-monif.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-{{ item }}
    mode: 0644
    owner: root
    group: root
    force: yes
  with_items: "{{ rock_monifs }}"

- name: Configure local ifup script
  template:
    src: templates/ifup-local.j2
    dest: /sbin/ifup-local
    mode: 0755
    owner: root
    group: root
    force: yes
  notify: configure monitor interfaces

#######################################################
#################### Disable IPv6 #####################
#######################################################
- name: Disable IPv6 for all interfaces
  sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: 1l
    sysctl_file: "{{ rock_sysctl_file }}"

- name: Disable IPv6 for default interfaces
  sysctl:
    name: net.ipv6.conf.default.disable_ipv6
    value: 1
    sysctl_file: "{{ rock_sysctl_file }}"

- name: Disable IPv6 in SSHD
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: AddressFamily
    line: AddressFamily inet
  notify:
  - sshd restart

- name: Remove localhost6 from hosts file
  lineinfile:
    dest: /etc/hosts
    regexp: localhost6
    state: absent

#######################################################
#################### DNS Changes ######################
#######################################################
- name: Set hostname in hosts file
  lineinfile:
    dest: /etc/hosts
    insertafter: 127.0.0.1
    line: 127.0.0.2  {{ rock_fqdn }}  {{ rock_hostname }}

- name: Set system hostname
  hostname:
    name: "{{ rock_fqdn }}"

#######################################################
################## Setup Yum Repos ####################
#######################################################

- name: Setup EPEL repo
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: "{{ epel_baseurl }}"
    gpgkey: "{{ epel_gpgurl }}"
    gpgcheck: yes
  when: rock_online_install

- name: Manually trust CentOS GPG key
  shell: >
    rpm --import http://mirror.centos.org/centos/RPM-GPG-KEY-CentOS-7
  when: rock_online_install

- name: Setup Elastic repo
  yum_repository:
    name: elastic-5.x
    description: Elastic Stack repository for 5.x
    baseurl: "{{ elastic_baseurl }}"
    gpgkey:  "{{ elastic_gpgurl }}"
    gpgcheck: no
  when: rock_online_install

- name: Setup ROCK NSM repo
  yum_repository:
    name: rocknsm
    description: ROCK NSM repository for devel
    baseurl: "{{ rocknsm_baseurl }}"
    gpgkey:  "{{ rocknsm_gpgurl }}"
    gpgcheck: no
    cost: 750
  when: rock_online_install

- name: Setup local offline repo
  yum_repository:
    name: rocknsm-local
    description: ROCKNSM Local Repository
    baseurl: "{{ rocknsm_local_baseurl }}"
    gpgcheck: no
    cost: 500
  when: not rock_online_install

- name: Configure default CentOS online repos
  yum_repository:
    name: "{{ item.name }}"
    enabled: "{{ rock_online_install }}"
    description: "CentOS-$releasever - {{ item.name | title }}"
    mirrorlist: "{{ item.mirror }}"
    file:  CentOS-Base
  with_items:
  - { name: base, mirror: "http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=os&infra=$infra" }
  - { name: updates, mirror: "http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=updates&infra=$infra" }
  - { name: extras, mirror: "http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=extras&infra=$infra"}

- name: Configure RockNSM online repos
  yum_repository:
    name: "{{ item.name }}"
    enabled: "{{ rock_online_install }}"
    description: "{{ item.name }}"
    baseurl: '{{ item.baseurl }}'
    file: rocknsm
  with_items:
    - { name: rocknsm_2_1, baseurl: https://packagecloud.io/rocknsm/2_1/el/7/$basearch }
    - { name: rocknsm_2_1, baseurl: https://packagecloud.io/rocknsm/2_1/el/7/SRPMS }

...
